### ISSUE TITLE
Comment line syntax is broken after switch to JSON in manifest.json

### ISSUE THREAD

**Issue by manning-ncsa** [CMB-NCSA/spt3g_cutter#13]
https://github.com/CMB-NCSA/spt3g_cutter/blob/46e94dc7d28eed9a8567455652bd3d49fac44664/python/spt3g_cutter/cutterlib.py#L918

Now that the `manifest.yaml` file is `manifest.json`, the comment line containing the metadata about the file yields invalid JSON. Given that JSON does not actually support comments, we may need to move the information into a dedicated "metadata" object like 

```json
{
      "metadata": "Manifest file created by..."
      "bands": [
            "150GHz"
      ],
      "date_start": "None",
      ...
}
```

**Comment by menanteau** [comment]
Included in https://github.com/CMB-NCSA/spt3g_cutter/pull/14

**Comment by menanteau** [comment]
Included in: https://github.com/CMB-NCSA/spt3g_cutter/pull/14
